### ISSUE TITLE
the runtime error

### ISSUE THREAD

**Issue by zebrajack** [pedropro/CAPE#1]
According to the instruction, I target to the sequence folder, but the missing calibration file is weird.  Since the .xml file is already there.   My OS is ubuntu 14.04 64bit.

![image](https://user-images.githubusercontent.com/1118889/38606593-080cea76-3da9-11e8-8a51-48fde86effac.png)

**Comment by pedropro** [comment]
The right call should just be:
`./cape_offline 20 tunnel`

No need to specify the path. I am going to rectify the instructions to avoid ambiguity.

**Comment by pedropro** [comment]
Also (you probably know this by now) but the call needs to be done from the folder: CAPE/CAPE/build. where your executable should be. It's all in the instructions now.

**Comment by zebrajack** [comment]
Oh, yeah. I found it finally. though the cape_offline are build in CAPE/CAPE in default, I move it back to build folder. BTW, I didn't get the pose estimation, not mentioned the 3D model with depth fusion. so is it stripped-down version?

**Comment by pedropro** [comment]
Yes, this only includes the CAPE module used in the paper, which outputs the plane and cylinder segments and their estimated parameters. N.b. the parameters are not in the moment returned by the function call (TODO).

By pose estimation, I take it you mean camera pose estimation. Unfortunately, our VO is not public yet.

You can use the depth maps given by the OMG_depth_fusion (opensource) to feed CAPE as done in the paper. Both implementations are simple enough to integrate, however fusing temporally depth with a moving camera, requires camera pose...

**Comment by zebrajack** [comment]
OK. so the does the VO has plan to be public in the future. If yes, when will it be available probably?  I want to estimate the VO for scanning a cupboard box with relatively short trajectory.

**Comment by Osborn28** [comment]
@pedropro hi, I think changing "./cape_offline 20 tunnel" to "./cape_offline 20 seq_example" is better in README.
