### ISSUE TITLE
The mapping of cloud_array_organized

### ISSUE THREAD

**Issue by 0Jiahao** [pedropro/CAPE#3]
Hi! I am trying to use the CAPE detector for plane detection. I have a problem when converting the input data from organized pcl::PointCloud<PointXYZ> to Eigen::MatrixXf.

Base on my understanding, the input data is a width*height x 3 matrix (2D), but I don't know the order of it. It will be great if you can give me some hints on it!

**Comment by pedropro** [comment]
The order of `cloud_array` is row-major. However `cloud_array_organized` is sorted in a special cache-friendly way (by cell). This is done by calling the function `organizePointCloudByCell`. 

PCL uses Eigen underneath.  So I think you can just get the Eigen::MatrixXf by calling PCL function `getMatrixXfMap`, and then you can pass it to `organizePointCloudByCell` to obtain your 
`cloud_array_organized`

**Comment by 0Jiahao** [comment]
@pedropro Thanks for your reply! It works now;)
